name: Run API Tests - Ruby + ReportBuilder + Email

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 22 * * 5' # 19h BRT

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Instalar bundler e dependências
        run: |
          gem install bundler
          bundle install

      - name: Executar testes (gera JSON do Cucumber)
        run: |
          mkdir -p tmp
          bundle exec cucumber --publish-quiet --strict --format json --out tmp/cucumber.json || echo "tests_failed=true" >> $GITHUB_ENV

      - name: Criar script do ReportBuilder (silencia deprecation warnings)
        run: |
          cat > report_builder.rb <<'RUBY'
          # Silenciar avisos deprecados ANTES de carregar a gem
          begin
            if defined?(Warning) && Warning.respond_to?(:[]=)
              Warning[:deprecated] = false
              Warning[:experimental] = false
            end
          rescue
          end

          require 'report_builder'
          require 'time'

          ReportBuilder.configure do |config|
            config.input_path   = 'tmp/cucumber.json'
            config.report_path  = 'report_builder/report'
            config.report_types = [:html]
            config.report_title = 'Relatório Cucumber - ReportBuilder'
            config.color        = 'indigo'
            config.additional_info = { 'Gerado em' => Time.now.iso8601 }
          end

          ReportBuilder.build_report
          RUBY

      - name: Gerar HTML com ReportBuilder (sem warnings)
        run: |
          mkdir -p report_builder
          RUBYOPT='-W0' ruby report_builder.rb 2>/dev/null

      - name: Definir data e nome do relatório
        id: vars
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "filename=Report_Cucumber_$(date +'%Y-%m-%d').zip" >> $GITHUB_OUTPUT

      - name: Compactar relatório
        run: |
          cd report_builder
          zip -r "${{ steps.vars.outputs.filename }}" report.html

      - name: Criar corpo do e-mail
        run: |
          echo "📊 Relatório de Testes Automatizados (Cucumber/ReportBuilder)" > email_body.txt
          if [[ "${{ env.tests_failed }}" == "true" ]]; then
            echo "❌ FALHAS detectadas nos testes." >> email_body.txt
          else
            echo "✅ Todos os testes passaram com sucesso!" >> email_body.txt
          fi
          echo "" >> email_body.txt
          echo "Anexo: ${{ steps.vars.outputs.filename }}" >> email_body.txt

      - name: Enviar relatório por e-mail (anexo ZIP)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Relatório Cucumber - ${{ steps.vars.outputs.date }}
          to: silvio.aulik@gmail.com
          cc: staulik10@gmail.com, qatadeu@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: file://email_body.txt
          attachments: |
            report_builder/${{ steps.vars.outputs.filename }}

      - name: Finalização
        run: echo "✅ Pipeline finalizada com sucesso e relatório enviado por e-mail!"
