name: Run API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '42 19 * * 5'  # Toda sexta-feira às 19h (horário de Brasília / UTC-3)

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Altere conforme necessário

      - name: Instalar bundler e dependências
        run: |
          gem install bundler
          bundle install

      - name: Executar testes e gerar relatório
        run: RUBYOPT='-W:no-deprecated' bundle exec cucumber -p default || true

      - name: Upload do relatório ReportBuilder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-dog-api
          path: report_builder/*.html

      - name: Upload do relatório Cucumber HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: report_builder/cucumber_report.html

