name: Run API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 22 * * 5'  # 19h de Brasília (UTC+3 → 22h UTC)

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Altere conforme necessário

      - name: Instalar bundler e dependências
        run: |
          gem install bundler
          bundle install

      - name: Executar testes (aceita falhas esperadas)
        run: RUBYOPT='-W:no-deprecated' bundle exec cucumber -p default || true

      - name: Upload do relatório ReportBuilder
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-dog-api
          path: report_builder/*.html
