name: Run API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 22 * * 5'  # Toda sexta-feira às 19h (horário de Brasília)

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Altere se estiver usando outra versão

      - name: Instalar bundler e dependências
        run: |
          gem install bundler
          bundle install

      - name: Executar testes
        run: bundle exec cucumber -p default

      - name: Upload do relatório ReportBuilder
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-dog-api
          path: report_builder/*.html
